### ISSUE TITLE
Panic when websocket connection received

### ISSUE THREAD

**Issue by mrichman** [gorilla/websocket#106]
As soon as I connect to my service via a curl request, I get a panic:

`curl -v http://localhost:3000`

`panic: runtime error: invalid memory address or nil pointer dereference`

Full stack trace and source are in this gist: https://gist.github.com/mrichman/619d038f9b0553b127d6

What am I doing wrong?

**Comment by garyburd** [comment]
Handle all errors returned from the functions.

The call to upgrader.Upgrade returns a nil connection and  an error explaining that the request is not a websocket connection.  The call to conn.ReadMessage panics because the connection is nil.

If a valid handshake is received and the client later disconnects, then the for loop will spin using 100% of a CPU.  To prevent this, break out of the for loop when conn.ReadMessage returns an error,

[The Gorilla echo example](https://github.com/gorilla/websocket/tree/master/examples/echo) shows how to write a simple echo server.

**Comment by mrichman** [comment]
Thanks. Rookie mistake.
