### ISSUE TITLE
Don't close network connection on write error

### ISSUE THREAD

**Issue by garyburd** [gorilla/websocket#177]
See #176 
- protect Conn.writeErr with mutex.  
- remove Conn.closeSent and set Conn.writeErr instead
- set Conn.writeErr on all network connection write errors
- add messageWriter.err
- move Conn.FlushFrame to messgeWriter.FlushFrame and untangle error handling.
- bonus: use sync.Pool for write buffer

**Comment by KiranRG** [comment]
Btw, can I ask, why are you looking at protecting 'writeErr' modifications with a mutex? Technically, it should only be read/written to from the "write paths" and given that the write-paths cannot be called concurrently, this should not be necessary.

I know there is at least one path, where I know this not to be true -- which is where in the read-path, when it encounters a "close frame", it _automatically_ responds back with a close-frame. And this is really the other gorilla-websocket behaviour that is causing issues for us.

**Comment by garyburd** [comment]
WriteControl can be called concurrently with the other write API calls.

The protocol requires an endpoint to respond to a close frame with a frame. This cannot be changed without breaking most applications that use the package.

**Comment by KiranRG** [comment]
True -- WriteControl can be called concurrently; and that will need to be special-cased.

I was proposing that the websocket layer convey to the the application that a close-frame was received (via an error-code) and leave it to the application to respond with a close-frame.

Here's our scenario -- we have built a "buffering"/streaming layer atop the websocket, that supports WriteMsg, Flush, ReadMsg. WriteMsg would buffer messages internally until the buffer is full, at which point it would call Flush. Flush (which can be called by the application any time too), will flush out all buffered messages after serializing them into a single "payload" for websocket. ReadMsg reads a payload, deserializes them and returns one message at a time from the buffer, until it is empty, at which time it reads another payload from the wire. Pretty standard buffering mechanism.

Because the websocket layer is automatically responding with a close-frame, the server does not get an opportunity to flush out any messages that it has currently buffered (from previous WriteMsgs calls that have not been flushed).

Ideally, the client should be able to send a close-frame (indicating intent to go away), in response to which our server would flush out any buffered messages, and send a close-frame back before closing the connection. But this cannot be implemented due to the automatic close-frame -- our "tail" of buffered messages are lost!

It is great that the gorilla-websocket provides the ability to send a custom close-frame, but I think auto-responding internally with a close-frame is forcing "policy" on the application.

**Comment by KiranRG** [comment]
Gary, I have created a separate issue to track/discuss this: #178. Feel free to update title/content, etc.

**Comment by garyburd** [comment]
Fixed by 80a0029a6599f5a3c2f1b5b7f1faf215d6e979a4
