### ISSUE TITLE
Add prepareMessage and sendPrepared functions

### ISSUE THREAD

**Issue by jgupta** [gorilla/websocket#182]
We could improve performance in pub-sub or broadcast cases if functions such as prepareMessage and sendPrepared are added (especially in case of compression)

https://github.com/uWebSockets/uWebSockets/issues/141
http://autobahn.ws/python/_modules/autobahn/websocket/interfaces.html#IWebSocketChannel.sendPreparedMessage

**Comment by garyburd** [comment]
Describe what the feature does or link to an explanation of the feature.

**Comment by jgupta** [comment]
For e.g. a message X has to be sent to N number fo clients. By default, it would do same work (Framing, compression etc) N times.

**prepareMessage**: Prepare message to be sent, this would do framing, compression etc.
**sendPrepared**: Send already prepared message by skipping framing, compression assuming all of this is already done.

http://autobahn.ws/python/reference/autobahn.websocket.html#autobahn.websocket.interfaces.IWebSocketChannel.sendPreparedMessage
http://autobahn.ws/python/reference/autobahn.websocket.html#autobahn.websocket.IWebSocketChannel.sendPreparedMessage

https://github.com/uWebSockets/uWebSockets/issues/136
https://github.com/uWebSockets/uWebSockets/issues/141

**Comment by garyburd** [comment]
The benefit of the feature will be negligible for uncompressed messages.

The benefit of the feature will also be negligible when compression context takeover is used.  There is the option of resetting the compression context on a prepared message, but that cancels the benefits of context takeover. 

Because messages must be compressed wth a connection's negotiated value of the server window size, messages will be compressed lazily on first use of a given window size.  

The term "prepare" is not ideal for describing the feature because nothing is done when a message is "prepared".

**Comment by jgupta** [comment]
I understand. Is there any way we could improve performance when we are sending high throughput identical messages to over multiple clients?

**Comment by garyburd** [comment]
Fixed by 804cb600d06b10672f2fbc0a336a7bee507a428e.
