### ISSUE TITLE
help me i/o timeout

### ISSUE THREAD

**Issue by bino7** [gorilla/websocket#234]
after handler one message, throw out "read tcp [::1]:3000->[::1]:63819: i/o timeout" error,
i checked it is from websocket/conn.go func advanceFrame() {... p, err := c.read(2) ...}

**Comment by garyburd** [comment]
Are you [setting the read deadline](https://godoc.org/github.com/gorilla/websocket#Conn.SetReadDeadline) on the connection?

**Comment by bino7** [comment]
yes，it is just as same as chat example.

**Comment by garyburd** [comment]
Please share more information about what the application is doing. There's not enough information here to determine what's wrong.

**Comment by garyburd** [comment]
I/o timeout errors are expected when the read deadline is set. Please reopen if you can describe why the error is a problem and provide more details about how the application uses deadlines.

**Comment by yoiang** [comment]
Because netError is private is the expected way to test if a Timeout error has occurred to test that the error returned is not a Closed error using IsCloseError(...)?

**Comment by garyburd** [comment]
The only reason to check for CloseError is reduce logging noise.  Otherwise, applications should handle CloserError, timeout errors and network errors by closing connection and cleaning up.

**Comment by garyburd** [comment]
Applications should handle CloserError, timeout errors and network errors by closing the connection and cleaning up. 

Some applications reduce logging noise by only logging unexpected CloseErrors.  Logging unexpected CloseErrors is useful because these errors might be the result of an error in the application. An example is sending invalid UTF-8 in a text message.

What is the scenario where it's important to distinguish timeout errors from other errors?  Is there something the application will do differently for timeout vs some other network error?

**Comment by yoiang** [comment]
Right, because after a timeout the websocket is erroneous. 

The only scenarios where this would be nice is when wanting to know whether to refresh a connection because it was closed without an explicit desire to.

**Comment by garyburd** [comment]
An error of type `*CloseError` is returned when the peer explicitly closed the connection.
