### ISSUE TITLE
Ability to flush without ending the current message

### ISSUE THREAD

**Issue by AndreKR** [gorilla/websocket#259]
I am sending [gob](https://golang.org/pkg/encoding/gob/) over websockets. I had to decide whether to use the message framing offered by gob or the one from websocket.

A gob stream looks like this: `[type definitions][message][message]...`. If I would have used websocket framing, I would have to start a new gob stream for each message, which would mean the type definitions would be transferred with every message. So I decided to use the gob framing.

If I see this correctly, the `websocket.messageWriter` buffers the current message until it is `Close()`'d. So for my messages to arrive in a timely fashion, I would need a way to flush this buffer after each message:
```go
w, err = conn.NextWriter()
enc := gob.NewEncoder(w)

for _, msg := range messages {
  err = enc.Encode(msg)
  err = w.Flush()
}
```

FYI, the `http.ResponseWriter` implements a similar feature like this: `w.(http.Flusher).Flush()`.

That means if for some reason the return type of `NextWriter()` can't be changed (currently it returns an interface instead of a concrete type and I don't understand why), it would still be possible like this:

```go
w, err = conn.NextWriter()
enc := gob.NewEncoder(w)

for _, msg := range messages {
  err = enc.Encode(msg)
  err = w.(websocket.Flusher).Flush()
}
```

**Comment by elithrar** [comment]
What does the code on the receiving end look like? As long as each side
uses the same encoder / decoder instance, you shouldn't need to re-send
type definitions, even across discrete messages.

**Comment by AndreKR** [comment]
```go
_, r, err = conn.NextReader()
dec := gob.NewDecoder(r)

for {
  err = dec.Decode(&msg)
  fmt.Println(msg)
}
```

**Comment by garyburd** [comment]
The unit of delivery is a message.

Layer a stream on top of messages.  Implement io.Writer using [WriteMessage](http://godoc.org/github.com/gorilla/websocket#Conn.WriteMessage). Implement io.Reader similar to [io.MultiReader](https://github.com/golang/go/blob/445652f45361d4935a828f394d7f0322faa6d9ad/src/io/multi.go#L17-L42), but call  [NextReader](http://godoc.org/github.com/gorilla/websocket#Conn.NextReader) to get the next reader instead of [taking the next reader from the slice](https://github.com/golang/go/blob/445652f45361d4935a828f394d7f0322faa6d9ad/src/io/multi.go#L20-L25).

If the client is not a web browser, then there be simpler approaches than using websockets.  If data is only sent from server to the client, then write the gob stream to the the HTTP response body.

**Comment by AndreKR** [comment]
> Layer a stream on top of messages. Implement io.Writer using WriteMessage. Implement io.Reader similar to io.MultiReader, but call NextReader to get the next reader instead of taking the next reader from the slice.

Indeed, that would work. It's basically using NextWriter() to flush. But don't you think with an explicit flush it's a much clearer interface, so whoever reads the code next will immediately see what the intention was? Also there's probably more overhead when calling NextWriter after every Write, but I guess that's negligible.

> If the client is not a web browser, then there be simpler approaches than using websockets. If data is only sent from server to the client, then write the gob stream to the the HTTP response body.

I have a "client" and a "server". The client can open a connection to the server but not the other way around. Every now and then an event happens at the server and it needs to be relayed to and confirmed by the client. I figured websockets lead to the cleanest implementation for this kind of message flow. And unlike a simple TCP connection they come with automatic SSL.

**Comment by garyburd** [comment]
Flushing partial messages is not required by the protocol. The unit of delivery is a message. 

I am not aware of any uses of the protocol that requires partial flush.

The stream layer is a few lines of code and can be written so that the intention is clear.

I suggest reading and writing gob streams on a [hijacked connection](http://godoc.org/net/http#Hijacker).
