### ISSUE TITLE
Which Upgrade method/function is deprecated?

### ISSUE THREAD

**Issue by fuzzybear3965** [gorilla/websocket#263]
I've submitted #262 to help distinguish between the function websocket.Upgrade and the method websocket.Upgrader.Upgrade. The documentation was a bit confusing as to which should be used.

**Comment by garyburd** [comment]
The Upgrade function comment says that the function is deprecated. The function is described as the "deprecated Upgrade function" outside of the function's comment.

Readers should understand that deprecated functions are not recommended.

The first paragraph in the overview section does create some confusion because it uses the term function instead of method.  Rewriting it as 

> The Conn type represents a WebSocket connection. A server application calls the Upgrader.Upgrade method from an HTTP request handler to get a *Conn.

may help clear up the confusion.

Updating the Upgrade function doc comment to use [the standard deprecation syntax](https://blog.golang.org/godoc-documenting-go-code) may also help.

> To signal that an identifier should not be used, add a paragraph to its doc comment that begins with "Deprecated:" followed by some information about the deprecation. There are a such few examples in the standard library.

**Comment by fuzzybear3965** [comment]
Your rephrasing of the first paragraph in the Overview section does help, and your revision is a good one.

I hadn't noticed the godoc deprecation syntax. That would be nice to use. Unfortunately, it doesn't seem to be used much even by golang developers.

I also think that my emphasis regarding the origin policy checking could help users. I don't think it will hurt anything.

**Comment by garyburd** [comment]
> Unfortunately, it doesn't seem to be used much even by golang developers.

If you are referring code maintained by the Go Team, then file an issue when you find code that does not use the syntax.  They updated a number of comments to use the syntax, but may have missed some.

**Comment by fuzzybear3965** [comment]
> then file an issue when you find code that does not use the syntax

I'll do that.  I found a [number of such instances](https://golang.org/search?q=deprecated) (I didn't find a single instance - after reviewing ~20 of those search results - where `Deprecated:` was used).

I see you've reviewed the pull request. I'll make the suggested changes and push another commit.
