### ISSUE TITLE
Why not to implement Write and Read interface to follow io standard defination.

### ISSUE THREAD

**Issue by hanbaga** [gorilla/websocket#387]
the reason is that can communicate with some io standard library normally.

**Comment by elithrar** [comment]
Much of this package either accepts standard library interfaces, or returns
them - e.g. https://godoc.org/github.com/gorilla/websocket#Conn.NextReader

Convenience methods like WriteJSON just wrap those.

Do you have a concrete example of where the package API is not working for
you?

**Comment by hanbaga** [comment]
"NextWriter returns a writer for the next message to send. The writer's Close method flushes the complete message to the network."


I want flush the message to Network when I call write not waiting Close.

I want io.Copy(NextWriter,  SomeNetworkReader)  work normally.

**Comment by dottyjones** [comment]
The package supports the standard io package interfaces in the context where it makes sense. The websocket protocol is message based.  This package provides io.WriteCloser for writing to a message and io.Reader for reading from a message. 

You can implement a io.ReadWriter on top of the message-based API in this package in a few lines of application code.  Your application can decide how to handle all of the corner cases.  For example, you can decide what happens when a message is smaller or larger than the buffer passed to io.Read.
