### ISSUE TITLE
Improve "Origin" check logic to compare scheme & ports

### ISSUE THREAD

**Issue by battlmonstr** [gorilla/websocket#398]
This function - "checkSameOrigin" here:
https://github.com/gorilla/websocket/blob/master/server.go#L74

compares the request `Host` header with the request `Origin` header.

I'm using a client where the `Host` header contains the port (which is legit [according to these docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host)).
So it has:

```
Host: example.com:443
```
(actually the client code sets it here: https://github.com/daltoniam/Starscream/blob/master/Sources/WebSocket.swift#L590 )

The Origin header contains scheme and might contain the port ([see spec here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin)). In my case it looks like so:

```
Origin: wss://example.com
```

Since `wss://example.com` is equivalent to `wss://example.com:443`, it should match the Host above.

I propose to enhance checkSameOrigin to support schemes, ports and default ports.

**Comment by garyburd** [comment]
I agree that it's helpful to normalize port numbers.  Something like this should work:

```
func checkSameOrigin(r *http.Request) bool {
	origin := r.Header["Origin"]
	if len(origin) == 0 {
		return true
	}
	u, err := url.Parse(origin[0])
	if err != nil {
		return false
	}
	if equalASCIIFold(u.Host, r.Host) {
            return true
        }
        host := r.Host
        switch u.Scheme {
        case "http": host = strings.TrimSuffix(host, ":80")
        case "https": host = strings.TrimSuffix(host, ":443")
        }
        return equalASCIIFold(u.Host, host)            
}
```

**Comment by battlmonstr** [comment]
This code doesn't seem to cover all the cases. Port should be examined, and ws(s) should be treated.

I would structure the logic like so:

	originScheme := ... // if origin contains scheme, use it, otherwise default to "ws"
    originHost := ...
	originDomain := ... // cut off the port, keep just the domain
	originPort := ... // if originHost contains port, use it, otherwise if originScheme is secure use 443, otherwise 80

	requestScheme := r.URL.Scheme
	requestHost := r.URL.Host
	requestDomain := ... // cut off the port, keep just the domain
	requestPort := ... // if requestHost contains port, use it, otherwise if requestScheme is secure use 443, otherwise 80
	
	sameScheme := convertWSToHTTPScheme(originScheme) == requestScheme 
		// in convertWSToHTTPScheme "ws" becomes "http", "wss" becomes "https" (simple switch)
	sameDomain := equalASCIIFold(originDomein, requestDomain)
	samePort := originPort == requestPort

	return sameScheme && sameDomain && samePort

This could probably be simplified, but it's nice to keep the structure of the last condition for clarity.

**Comment by garyburd** [comment]
Browsers set the origin scheme to `http` or `https`.  What is a scenario where the scheme `ws` or `wss` makes sense as an origin?

It is not possible to derive the request scheme from an `*http.Request`.  The field `r.URL.Scheme` is set to the empty string.

The `r.URL.Host` field is set to the empty string.

**Comment by battlmonstr** [comment]
> What is a scenario where the scheme ws or wss is used as an origin?

Starscream iOS client does that. See the link in the description. Not sure what is their reasoning.

> It is not possible to derive the request scheme from an *http.Request.

Bummer... There should be a way to check if the current connection has TLS or not? In practice "sameScheme" could be probably replaced by "sameSecurityLevel":

	originIsSecure := ... // true if Origin has "wss:" or "https:" prefix
	requestIsSecure := ... // true if current request is handled over a TLS connection

	sameSecurityLevel := originIsSecure == requestIsSecure
	...
	return sameSecurityLevel && sameDomain && samePort

This should be fine, because we don't care about non-WebSocket-related schemes.

> r.URL.Host are set to ""

Maybe you have it in the "Host" HTTP header in r.Header ?

**Comment by elithrar** [comment]
You can check for the presence of a *tls.Config on the request, but that
does not account for a large number of cases where the application is not
terminating TLS, and is behind a proxy - e.g. many cloud environments, load
balancers, dev environments, etc.

**Comment by garyburd** [comment]
The origin header specifies the source of a script running in a web browser.  If I understand the Starscream code correctly, there are a couple issues with the client:

- The client should not require or force an origin header.
- Because browser sources are either  "http" or "https", the use of "ws" and "wss" in the origin scheme is unexpected.

Here's an improved and safer check than the one I proposed earlier:

```
var defaultPorts = map[string]string{"http": "80", "https": "443"}

func checkSameOrigin(r *http.Request) bool {
	origin := r.Header["Origin"]
	if len(origin) == 0 {
		return true
	}
	u, err := url.Parse(origin[0])
	if err != nil {
		return false
	}
	if equalASCIIFold(u.Host, r.Host) {
		return true
	}

	defaultPort, ok := defaultPorts[u.Scheme]
	if !ok {
		return false
	}

	host, port, err := net.SplitHostPort(u.Host)
	if err == nil {
		return port == defaultPort && equalASCIIFold(host, r.Host)
	}

	host, port, err = net.SplitHostPort(r.Host)
	if err == nil {
		return port == defaultPort && equalASCIIFold(u.Host, host)
	}

	return false
}
```

In addition to proxy scenarios, checking [Request.TLS](https://godoc.org/net/http#Request.TLS) does not handle the case where TLS is handled in the listener passed to [Server.Serve](https://godoc.org/net/http#Server.Serve) and friends.

**Comment by battlmonstr** [comment]
@garyburd your code is correct for web clients, but you know that it fails with Starscream. It is a nuissance.

Here is a use case I have in mind:
1. You invite a full-stack consultant who develops an iOS app + a backend using Starscream + gorilla WS. He uses a default config and gets an error from checkSameOrigin. So he replaces it with a custom implementation that always returns true. This is quick and formally correct. Remember that this guy is not a security/web/websocket expert, he's eager to implement business domain logic and is limited in time.
2. You expand to the web and invite a JS developer. He implements a web client. Everything works.
3. Time passes and you get an XSS, because nobody touched checkSameOrigin ever since 1.

This use case happened to me in practice, and I'm sure someone could trip on that too.

So I'm just trying to point out that if the default config worked out of the box for all major clients, it would be beneficial for everyone, and our servers would be safer.

> that does not account for a large number of cases where the application is not
terminating TLS, and is behind a proxy - e.g. many cloud environments, load
balancers, dev environments, etc.

Yes, I see the point with request protocol not being correct, because end to end encryption is not always available. So how can the scheme be checked then? To me the ideal way would be to implement a correct behaviour by default and make it easily customizable for other configurations. Maybe there's a way to make this function public and pass in some extra parameters about what to check and what not to check?

**Comment by garyburd** [comment]
Regarding the use case:  Setting a check origin function is a workaround for the issue in Starscream.  Fix that issue.

There's no need for an isWebClient argument the checkSameOrigin. If the origin header is set, then server should assume that the client is a web browser and handle it as such.

There are several options for a general purpose check origin function:
- Use XFF / XFP or similar headers.
- List of trusted domains.
- Is request host a trusted domain or not?
- Is insecure http: origin allowed?

There are probably more knobs to turn than these.  At some point, it's easier for the developer to just write a function than it is to understand a number of options and how they interact with each other.

**Comment by garyburd** [comment]
The issues to fix in Starscream are:

1. Don't require an origin header.
2. If origin header is set, then use an expected scheme (http or https).

The first fix works with this package as is.  The second fix requires port normalization as in my most recent function.

It looks like the application can work around the issues in Starscream by supplying an origin header in the request.

**Comment by battlmonstr** [comment]
@garyburd could you please post that issue to the [Starcream repo](https://github.com/daltoniam/Starscream/issues) from your own name? You have more authority than me on the subject. I will support you there with evidence.

**Comment by garyburd** [comment]
@battlmonstr:  Refer the client developer to the RFC.  The RFC discusses the Origin header in sections 1.3, 1.6 and 10.2.  

Because the current check works with known browsers, I am inclined to leave the code as is.

**Comment by battlmonstr** [comment]
I assume this is the RFC - https://tools.ietf.org/html/rfc6455

Quoting here:
> when the WebSocket Protocol is used by a dedicated client directly, the origin model is not useful, as the client can provide any arbitrary origin string

This is the case with that client library.

And then this:
> If the origin indicated is unacceptable to the server, then it SHOULD respond ... with a reply HTTP 403 ... The intent is not to prevent non-browsers from establishing connections but rather to ensure that trusted browsers ...

In this case you know that this is not a web browser contacting you, because scheme is not http(s). So in order to follow the intent of the RFC and still let such clients in I think it is fine to just ignore the check, i.e. you could add:

    if ((origin.scheme != "http") && (origin.scheme != "https")) {
        // for non-browser clients the Origin check is meaningless
        return true; 
    }

In this case you are doing it by the book, because RFC says "it SHOULD", and you are still safe, because you know it's not a web browser sending this in.

Ideally they should remove that header too, because that seems silly to send Origin in as it proves nothing.
In the meantime I'm sure that there's a ton of clients deployed in the wild with that header though, and it is easier to upgrade the servers than the clients.

**Comment by garyburd** [comment]
The checkSameOrigin function implements the same-origin policy as a safe default for applications.

Limiting the same-origin check to http and https protocols is unsafe. An application served from ftp://evil-server/ can connect to ws://victim-server/ with this limitation.

Starscream is the only client that I know of that sends a problematic Origin header. The problem is not widespread.

There are three choices:

- Change the client application to specify an Origin header that works with checkSameOrigin.
- Fix the issue with the Starcream library.
- Provide a CheckOrigin function.

**Comment by stevenscott89** [comment]
@battlmonstr Did you contact the developer of Starcream regarding the issue?  If so, what did they say?

**Comment by battlmonstr** [comment]
@stevenscott89 No, I didn't, feel free to do it. I still think it's better to fix it on the server side, because even if they fix it will take a year until all clients get updated (so it's not a fix & forget operation for devops). It's a matter of convenience. There's no hard write or wrong here other than "maintainer is always right".

**Comment by stevenscott89** [comment]
Security trumps convenience. Relaxing the origin check may introduce a security vulnerability.

There is a hard wrong and right here. The RFC is clear about the conditions where a non-browser client may send the origin header and how the origin string should be constructed.  Nothing in the discussion so far indicates that your application meets those conditions, and even if the application does meet the conditions, the origin string is not constructed per the RFC.

The quote from the RFC a couple of comments back explains why the origin model is not useful for non-browser clients.  The quote does not say that non-browser clients may send arbitrary origin strings as Starscream does.

I asked if you contacted the client library author in case they were giving pushback on fixing the issues. I'd jump into the discussion if they were.

This issue should be closed. The issue should be fixed in the client and there are ways for OP to work around the issue should the client not be fixed (specify the origin string in client or provide own check origin function).

**Comment by battlmonstr** [comment]
The solution above does not relax security in any way, because like you say, it only matters for browsers, and they do have a normal "http(s)" scheme.

Secondly, you say that Starscream violates RFC. I think this is an exaggeration. I want to believe you, but I don't see how it violates RFC. Please tell me where in the RFC it says that 1) sending Origin from a non-browser client is forbidden, and 2) where it says that "ws(s)" schemes are forbidden in Origin? If it says so somewhere in clear text, then you are right, and the client is hardly wrong, and I would love to help fixing it. Otherwise it is just an interpretation, and up to discussion.

In the meanwhile there are probably thousands if not millions of such clients in the wild. To me this issue is not so much about having a workaround, but having support for Starscream out of the box reducing configuration burden, because when non-security savvy people start configuring security they usually do mistakes. With that said I believe that supporting Starscream out of the box actually improves security.

**Comment by stevenscott89** [comment]
[Section 4.1 of the RFC](https://tools.ietf.org/html/rfc6455#section-4.1) says:

>    8.   The request MUST include a header field with the name |Origin|
        [RFC6454] if the request is coming from a browser client.  If
        the connection is from a non-browser client, the request MAY
        include this header field if the semantics of that client match
        the use-case described here for browser clients.  The value of
        this header field is the ASCII serialization of origin of the
        context in which the code establishing the connection is
        running.  See [RFC6454] for the details of how this header field
        value is constructed.

Your application does not have the semantics of a browser client, therefore your application may not send the origin header.  Even if the application does have the required semantics, Starsceam creates the origin string from the request URL, not from origin context of the application (whatever that may be).

> it only matters for browsers, and they do have a normal "http(s)" scheme.

The RFC is clear that the origin header may only be sent browsers or applications with browser semantics.  It's dangerous to assume that the client is not a browser or similar because the origin string does not make sense.

**Comment by battlmonstr** [comment]
The RFC quote you provide doesn't say anything specific about non-browser clients, which don't follow browser semantics. Browsers and applications with browser semantics MUST or MAY send it, but it doesn't mean that all other apps can't send it. It is unspecified here. You seem to jump to conclusion that if it is not specified - it is forbidden. Why so?

> It's dangerous to assume that the client is not a browser or similar because the origin string does not look like one sent by a browser.

I agree about that in general, but in this case the scheme is particularly "ws", which means "web socket over HTTP", or "wss", which means "web socket over HTTPS". If you treat them equally to http/https - it seems to be safe then, isn't it?

**Comment by elithrar** [comment]
WebSockets don't run "over" HTTP(S). The HTTP protocol is used for the handshake, which is the agreement that the server & client can speak the WebSocket protocol over the TCP connection originally set up for HTTP (this is also why HTTP2 to WS is complex, due to HTTP/2 streams).

I think this discussion may have run its course. @battlmonstr - I strongly suggest you at least initiate the conversation with the Starscream developers (which has not been done yet), and use the tools available in this library (`CheckOrigin`) to manage in the meantime.

Making major assumptions about the "default" state of the [Origin triple](https://tools.ietf.org/html/rfc6454#section-5) adds a lot of risk. The only "assumption" you should make [as per the Web Origin RFC](https://tools.ietf.org/html/rfc6454#section-4.6) is on port, under certain conditions (default port for a scheme).

**Comment by battlmonstr** [comment]
> WebSockets don't run "over" HTTP(S)

I'm sure you know what I meant. The point is that they utilize the same default port for these schemes.
