### ISSUE TITLE
Is there "cpu leak" possible??

### ISSUE THREAD

**Issue by 756445638** [gorilla/websocket#410]
I have very high cpu usage on windows some times, Is there any chance cause by this library???

**Comment by elithrar** [comment]
Have you profiled your application?
https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/

**Comment by 756445638** [comment]
no,the machine have high cpu usage is at another place.

**Comment by FZambia** [comment]
@756445638 hi, without profile information its impossible to say what caused high CPU usage. This can be caused by code that works with Websockets, but also by some other piece of your application code base. Maybe it's time for your application to scale, maybe there is a room for optimization. From what I can say this library is pretty predictable in resource usage and resource growth only occur when more connections or messages appear in application - but this is an expected effect.

So what you need is add more metrics and do profiling.

**Comment by 756445638** [comment]
looks , it is my fault, thanks very much.
