### ISSUE TITLE
gorilla always encouter unexpected EOF, but google's version works well

### ISSUE THREAD

**Issue by vegertar** [gorilla/websocket#43]
For easy to deployment, I use golang to re-implement my python's websocket client but always encouter the unexpected EOF error.
Actually, my programs implement a pipeline of HTTP to websocket to HTTP, the websocket client keeps a long connection to a remote http server and proxy the remote request to the local http backend.
The test method is using the apache httpd tool: ab -n 10000 -c 300 http://remote-http-domain/
Both the python client and the google's code.google.com/p/go.net/websocket are work well.
Sorry about I'm an one-day-old golang newer and the next Monday I must commit my codes, so I just issue this problem and no further advice.
Thanks for your consideration!

**Comment by ivoras** [comment]
Hello,

Is this issue still present? I seem to be getting the same error - suddenly, the only goroutine which reads (but there is another goroutine which only writes) gets the unexpected EOF errors.

**Comment by garyburd** [comment]
@ivoras The issue was in the OP's application. 

Here are some steps to debug your issue.  Please report back with the following in a new issue.

- Report the API that's returning the error. If the application calls ReadJSON, then [split the call into separate ReadMessage / UnmarshalJSON](https://github.com/gorilla/websocket/issues/43#issuecomment-60506809) calls to determine the source of the error.
- Report the client that you are using.
- Run the application with the race detector and fix any errors.
