### ISSUE TITLE
Q: read many messages in batch?

### ISSUE THREAD

**Issue by glycerine** [gorilla/websocket#554]
I am having some slow message processing (my TCP receive buffer isn't being emptied) and I wonder if I might be able to speed it up by receiving many websocket messages as a slice, at once.

Is there a way to use the gorilla API to get back all the available messages in one call?

**Comment by srybacki** [comment]
If the application uses a reasonably [sized read buffer](https://pkg.go.dev/github.com/gorilla/websocket?tab=doc#Upgrader.ReadBufferSize), than it is unlikely that a batch read will make any difference in performance. 

Is your application unable to keep up with data coming over the network when reading in a tight loop?  What is the read buffer size and typical message size for your application?

**Comment by glycerine** [comment]
If I have 1M small messages in my TCP buffer, doing one call through the gorilla stack instead of one million calls through the stack will be faster.

I know websocket messages are very sub-optimal for such situations, but I don't control the server.

> Is your application unable to keep up with data coming over the network when reading in a tight loop? 
Nope.

**Comment by srybacki** [comment]
Gorilla uses [bufio.Reader](https://pkg.go.dev/bufio?tab=doc#Reader) to amortize the cost of read operations on the underlying network connection.  A batching API will provide little or no additional benefit at that layer and below.

Because Gorilla's own code does not do a lot when reading messages as client, it will be difficult to squeeze more performance out if it. 

Is anything preventing you from using batching in your downstream processing?

**Comment by glycerine** [comment]
Ok. It may be that I am just seeing a very bad bug resulting in long delivery delays in gorilla under load. I will swap out the websocket implementation to check.

**Comment by srybacki** [comment]
The delivery delay bug is concerning.  Please share more information about the bug and how to reproduce it.

Is the request for the batch API separate from the bug, or did you propose the batch API as a fix for the bug?

**Comment by glycerine** [comment]
I don't have firm conclusions yet. Are there any existing load tests to determine capacity for gorilla?

**Comment by glycerine** [comment]
Also, if I want to collect all available messages before proceeding, is there a way to not block on a ReadMessage() call if nothing more is available?

**Comment by srybacki** [comment]
I don't know of any load tests.  

Read on a Gorilla connection is satisfied by returning data from the buffer or by issuing a read on the underlying network connection.  With the exception of ping message handling, there are no locks or goroutines that that can cause a delay on the read path. The ping handler sends a pong by calling [WriteControl](https://pkg.go.dev/github.com/gorilla/websocket?tab=doc#Conn.WriteControl).  WriteControl takes an internal write lock when writing to the underlying network connection.  Is the server sending a large number of pings and is the application itself writing to the connection?  That can explain the delays.

Go network connections do not have a non-blocking mechanism for determining if data is available.  Because Gorilla reads through to underlying network connection, it follows that Gorolla websocket connections do not have non-blocking mechanism for determine if a message is available.

To batch messages in an application, use one goroutine to pump messages from the websocket connection to a queue.  Use another goroutine to take everything in the queue as a batch and process it.

**Comment by glycerine** [comment]
> Go network connections do not have a non-blocking mechanism for determining if data is available.

On a regular net.Conn, I usually use a read timeout of 10 millisecond for this. If a timeout error is returned, we know there wasn't anything available.

**Comment by srybacki** [comment]
> because of the following strange choice

It would be great if Gorilla did not have this limitation, but the choice is not strange. See https://github.com/gorilla/websocket/issues/474 for background.
