### ISSUE TITLE
[question] Using websockets without using mask

### ISSUE THREAD

**Issue by romayalon** [gorilla/websocket#560]
**Describe the problem you're having**
> According to #188 - you have answered:
"The error indicates that the client did not set the frame-masked header bit to 1 as required by the protocol".
According to  the protocol: "All frames sent from client to server have this bit set to 1. "  
The RFC6455 protocol does not mention the following situation: 
sending frames from client to server over TLS. Sending and handling mask on top of those frames is unnecessary.
Also, Sending frames from client to server without mask can be done for example in node js that do not enforce this.
Do you have any suggestion to this missing implementation?
…

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!
```
// 4. Handle frame masking.

	if mask != c.isServer {
		return noFrame, c.handleProtocolError("incorrect mask flag")
	}
```
> Hint: wrap it with backticks to format it

…

**Comment by srybacki** [comment]
The RFC is explicitly states that masking is required with TLS.  Here's s a quote from [Section 5.1 of the RFC](https://tools.ietf.org/html/rfc6455#section-5.1):

>  (Note that masking is done whether or not the WebSocket Protocol is running over TLS.)  The server MUST close the connection upon receiving a frame that is not masked. 

Fix the broken client library or client application.

**Comment by elithrar** [comment]
Closing out - please let us know if you have any more questions around this.

**Comment by ioquatix** [comment]
I have one additional point which might be worth discussing.

In my particular case, I was seeing this error when sending a pong response

```
00000000  8a 00
```

Because there is no payload, there doesn't seem to be any point to send a mask, because there is nothing to mask. It adds 4 bytes of overhead and I can't see why this is necessary. You could probably argue both ways, but I'm not sure the RFC clarifies this. In any case, technically speaking I can't see any reason to send a mask on such a frame. Thoughts?
