### ISSUE TITLE
Web socket server getting late notification when client disconnect because of network off.

### ISSUE THREAD

**Issue by sainath-everest** [gorilla/websocket#569]
**Description :** 
When web socket client disconnect  due to network off, server not able to notify immediately. Server getting read time out error after specific amount of time(approx. 2 minutes).

**Versions:**
go version go1.13.4
socket connection : Gorilla web-socket

**My Code block for writing message to client.**

```
err := c.Conn.WriteJSON(message)
			if err != nil {
				log.Println("offline test: before adding offline msg to db ", message)
				database.StoreOfflineMessages(message)
				c.Conn.Close()
                     }
```

When writing message to client if any error come, those messages will be store in database.So when there is network off at client side and if any other client send message to client which has no network, server will still assuming that client is alive and sending messages.Because of that some data loss is happening.
Is there any solution to handle this in gorilla web-socket ?

**Comment by srybacki** [comment]
`c.Conn.WriteJSON` returns with no error when the data is successfully written to the operating system's connection.  There's no guarantee that the data will be received by the peer application. 

If you must know that the peer received the message, then have the peer application send a message acknowledging receipt of the message.

**Comment by sainath-everest** [comment]
But for sending acknowledgment ,at that moment peer application does not have any network right So we need to handle this server side only.

**Comment by srybacki** [comment]
If the server does not receive acknowledgment of the message within some timeout, then the server should assume that the peer did not receive the message.

**Comment by themartorana** [comment]
This is what `SetReadDeadline` and `SetWriteDeadline` are for - ostensibly. I find that `SetReadDeadline` is much more reliable, and run a concurrent ping that sets short read deadlines and accepts any downstream bytes as acceptable. Here are the basics:

Ping -> SetReadDeadline(short) -> Any bytes at all -> SetReadDeadline(0)

It's a weird way to detect broken connections, but I find I'll often run into long-wait timeouts because the underlying OS socket hasn't detected a disconnect yet. Deadlines help me augment that understanding and allows me to manually shoot down connections that haven't received information in a while

**Comment by elithrar** [comment]
Closing this out - @themartorana's advice is solid here. Please feel free to re-open if any questions.
