### ISSUE TITLE
[question] http: Accept error

### ISSUE THREAD

**Issue by Nix1304** [gorilla/websocket#572]
**Describe the problem you're having**

After some time of my program working, im getting a `http: Accept error: accept tcp [::]:4000: accept4: too many open files; retrying in 1s`. Im use a default net/http

**Versions**
go version go1.13.5 darwin/amd64

**Comment by srybacki** [comment]
The application is breaching the file descriptor limit.  This could be because of a file descriptor leak in the application or it could be because the process is not configured to handle the number of open file descriptors.

Is the number active websocket connections near the file descriptor limit reported by `ulimit`?  If so,  there are many resources on the web on how to increase the limit.

If not, then look for a file descriptor leak in the application.  Use `lsof` to determine what kind of file descriptors are leaking.  Confirm that the application [closes websocket connections](https://godoc.org/github.com/gorilla/websocket#Conn.Close). 

Because this package does not retain global references to anything with a file descriptor, it is unlikely that this package is responsible for the leak (if there is one).

**Comment by Nix1304** [comment]
when im write a `ulimit` command, im get `unlimited`. `lsof` show me 5 process when one connection. he maybe not closing, or gorutine maybe not stop. after disconnect process still working

**Comment by elithrar** [comment]
If you're still running into problems here:

* Make sure ulimit applies to the user the process is running as
* That you have persisted the settings - e.g. in `/etc/security/limits.conf` per https://serverfault.com/questions/610130/how-to-set-ulimit-value-permanently
* That you are closing connections appropriately.

If you are load-testing on the same machine it's still possible to starve the machine of ephemeral ports.
