### ISSUE TITLE
[question] How to run the test files

### ISSUE THREAD

**Issue by yuanlai** [gorilla/websocket#590]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
If I run the `go test client_test.go`, it report `undefined: hostPortNoPort` error for me.
…

**Versions**
> Go version: `go version`
1.14.2
…

**Comment by srybacki** [comment]
You specified the package as `client_test.go`.  The documentation  [on package specifications](https://golang.org/cmd/go/) says:

> If the arguments to build are a list of .go files from a single directory, build treats them as a list of source files specifying a single package.

The `client_test.go` does not compile as a package on its own because the file references symbols defined in other files.

Run `go help testflag` for information on how to specify a subset of tests to run.
