### ISSUE TITLE
[question] High CPU load on dial

### ISSUE THREAD

**Issue by l4zygreed** [gorilla/websocket#603]
While testing my code for websocket recreation to server, I noticed that when I dial to the server which is offline
```go
client, _, err = websocket.DefaultDialer.Dial(url, nil)
```
the Dial function cause CPU ~100% load until connection or timeout.

Can I somehow decrease CPU load when dial?

**Versions**
> Go version: 1.14.4

> package version: v1.4.1

> 2,6 GHz 6-Core Intel Core i7

**Comment by AllenX2018** [comment]
Hello~ Can you provide detailed codes and error information?

**Comment by l4zygreed** [comment]
server restarts sometimes so I need to reconnect to it
I use code kinda like this

```go
ws.Dialer = websocket.Dialer{
	Proxy:   http.ProxyFromEnvironment,
	HandshakeTimeout: 5 * time.Second,
}
```

```go
for err != nil || ws.Client == nil {
	ws.Client, _, err = ws.Dialer.Dial(url, nil)
	if err != nil {
		log.Println("Server not available:", err)
	}
	time.Sleep(10 * time.Second)
}
```

error is
```
2020/07/04 17:58:44 Server not available: dial tcp *ip here*:9090: i/o timeout
2020/07/04 17:58:49 Server not available: dial tcp *ip here*:9090: i/o timeout
```

when server in shutdown `Dialer.Dial()` try to connect to server and loads CPU to 99-100% until timeout.
But I need to have several processes with websockets that should be reconnected to different servers in future. 
I want to reduce CPU load when websockets trying connect to dead server.
![](https://cdn.discordapp.com/attachments/526136699856879628/728990801874518116/unknown.png)
Is there a way to lower CPU load or a better solution for waiting the server come alive?

**Comment by TaylorRex** [comment]
Is other code concurrently accessing `ws.Client`?   Run the application with the [race detector](https://golang.org/doc/articles/race_detector.html) and fix any reported errors.

**Comment by IngCr3at1on** [comment]
It's very possible that the issue here is related to the infinite loop in time.Sleep; there is a known issue that both time.Sleep and time.Ticker can result in high CPU usage, https://github.com/golang/go/issues/27707

If you check the comments this has been at least partially addressed for time.Ticker but not time.Sleep. So I'd recommend the following:

- ensure you are using a current go version (1.14 or later)
- replace sleep usage with a ticker
- run race detector as suggested by @TaylorRex and address anything it presents.
- reply here if issue persists

**Comment by TaylorRex** [comment]
@l4zygreed Did you run the application with the race detector and fix and reported problems?  

Is the goroutine that calls `ws.Dialer.Dial` the only application goroutine?  If not, is there evidence that `ws.Dialer.Dial` is using the CPU time and not some other goroutine?
