### ISSUE TITLE
May I know why the examples are using channel instead of just attaching a method function to send messages?

### ISSUE THREAD

**Issue by akmalhazim24** [gorilla/websocket#658]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
I'm curious why the examples uses channel and not regular functions?

**Comment by MonicaRJones** [comment]
To ensure that some operations are not executed concurrently, the examples use a single goroutine for executing those operations.  For example, the chat application uses a single "write pump" goroutine per connection to ensure that there are no concurrent writes to a connection.

The examples use channels for communication between these goroutines.

**Comment by In0ut123** [comment]
I got why the writePump and readPump run as goroutines, but does the hub need to use channels and run as a goroutine?
Would it work if instead of channels and the .run() function we replaced it with functions like .register(), etc. and these funcs were called inside of the pumps?
My initial thought was that it was built like this to avoid race conditions, but I can't find where in the code this could happen.

**Comment by MonicaRJones** [comment]
The single hub goroutine ensures that there's no concurrent access to [Hub.clients](https://github.com/gorilla/websocket/blob/c3dd95aea9779669bb3daafbd84ee0530c8ce1c1/examples/chat/hub.go#L11).

The hub goroutine can be replaced with plain methods for register, unregister and broadcast where each of the methods locks a mutex while accessing the map.  For whatever reason, the author of the example chose to use a goroutine to manage concurrency instead of a mutex.  Both approaches are valid.

**Comment by MonicaRJones** [comment]
Is  your question answered? If yes, then close the issue. If no, then please post a followup to my comment.
