### ISSUE TITLE
Pong message from dialer

### ISSUE THREAD

**Issue by rjpgt** [gorilla/websocket#665]
I understand that browsers automatically send pong messages in reponse to ping.

How do I send a pong message when I don't use a browser to make the connection, as for example, using `websocket.DefaultDialer` ?  Or, do I avoid ping messages when responding to a dialer ? The echo example does not use ping and pong messages.

Thanks.

**Comment by MonicaRJones** [comment]
The [documentation for this package](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Control_Messages) says:

> Connections handle received ping messages by calling the handler function set with the SetPingHandler method. The default ping handler sends a pong message to the peer.

Unless your application sets the ping handler, the connection automatically responds to pings with a pong.  Almost all websocket libraries handle the ping / pong automatically because the pong response is required by the protocol specification.

**Comment by rjpgt** [comment]
Ok.

**Comment by MonicaRJones** [comment]
Is  your question answered? If yes, close the issue. If no, please post a followup to my comment.

**Comment by rjpgt** [comment]
Sorry, yes, it is answered.
