### ISSUE TITLE
[question] Slow sending of a large number of messages

### ISSUE THREAD

**Issue by zebei** [gorilla/websocket#675]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

A lot of message send one websocket 
w.Write()  consume block after a while
case my send ch will piled up

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

1.15.6

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it
```
		case msg, _ := <-this.SendOpen:
			this.connect.SetWriteDeadline(time.Now().Add(this.writeWait))
			w, _ := this.connect.NextWriter(websocket.TextMessage)
			w.Write([]byte(msg.Ch))
			size := len(this.SendOpen)
			for i := 0; i < size; i++ {
				w.Write([]byte{'\n'})
				message := <-this.SendOpen
				w.Write([]byte(message.Ch))
			}
			w.Close()
```
SendOpen  channel will piled up 
message 2000/s

**Comment by MonicaRJones** [comment]
The websocket connection write performance is mostly limited by the write performance of the underlying network connection.  This package adds some framing around the application's data and writes it to underlying network connection.  There's not much that can be done to improve performance.

Redesign your application to handle the scenario where the speed of the network connection limits the application. The redesign is off topic here because it's unrelated to this package.
