### ISSUE TITLE
[question] Can return custom error before establish connection?

### ISSUE THREAD

**Issue by JimmyWang** [gorilla/websocket#700]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

If can return custom error to js before establish connection?
…

**Versions**
> Go version: `1.14`

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**

```
func echo(w http.ResponseWriter, r *http.Request) {
     params := r.URL.Query()
     id1 := params.Get("id1")
     id2 := params.Get("id2")
     // here get id1 & id2, Do the check before deciding whether to establish a connection
     //  js error & close event can NOT receive 500 code or error msg below:
     if checkIdfunc(id1,id2) {
         w.WriteHeader(500)
	 w.Write([]byte("error"))
         return
     }

    // open connection
    conn, err := upgrader.Upgrade(w, r, nil)
}
```

**Comment by MonicaRJones** [comment]
The application can return any response before calling Upgrade.  

Javascript code running in a browser cannot access the response because that enables cross domain requests.  To send an error to the client, upgrade the connection, write  a websocket message with the error and close the connection.

Other clients, such as the one in this package, provide access to the response.

**Comment by JimmyWang** [comment]
> The application can return any response before calling Upgrade.
> 
> Javascript code running in a browser cannot access the response because that enables cross domain requests. To send an error to the client, upgrade the connection, write a websocket message with the error and close the connection.
> 
> Other clients, such as the one in this package, provide access to the response.

Got it，thanks!
