### ISSUE TITLE
[question] Why in the example Chat, the Client has a chan with buffer size 256?  

### ISSUE THREAD

**Issue by AJRDRGZ** [gorilla/websocket#703]
**Describe the problem you're having**

> In this line [line 130](https://github.com/gorilla/websocket/blob/e8629af678b7fe13f35dff5e197de93b4148a909/examples/chat/client.go#L130)  of the example Chat, the Client is created with a buffer size of 256, I don't understand the reason of this arbitrary number, I think a buffered channel is used for assure not blocking the channel, so the Client can receive the message from the hub.broadcast, but why 256? Could be 1?

```go
client := &Client{hub: hub, conn: conn, send: make(chan []byte, 256)}
```

Can you please help me explained me the reason?

Thannks you

**Comment by FZambia** [comment]
Hello, this is a value which have been chosen by example author to have a reasonable size for a client message buffer.

See https://github.com/gorilla/websocket/blob/master/examples/chat/hub.go#L45 - this is a broadcast method which writes a message to a buffer of many clients. The important thing is that sending a message to individual connection should not block broadcast. Broadcast should be fast.

Value 1 is most probably too low for a task since it increases a chance of disconnecting a client if 2 messages sent to a connection quickly. But for a really slow sending rate in application it may work. 

It's not necessary to have a channel with fixed buffer size - it's also possible to have an unbounded queue for a connection and disconnect based on a queue size in bytes (if it exceeds some reasonable limit you choose yourself then connection considered slow and can be closed).

**Comment by AJRDRGZ** [comment]
I understand :smile: , Thanks you for your help @FZambia
