### ISSUE TITLE
Concurrent WebSocket connections

### ISSUE THREAD

**Issue by joelchen** [gorilla/websocket#72]
Wondering whether Gorilla WebSocket can have more than 600,000 concurrent connections on an M3.xlarge EC2 instance as compared to the implementation in http://www.jayway.com/2015/04/13/600k-concurrent-websocket-connections-on-aws-using-node-js.

Is a pool of WebSocket connections advisable as suggested in the answer of http://stackoverflow.com/questions/31134420/design-architecture-web-socket-one-connection-vs-multiple-connections, or multiple WebSocket connections advisable as suggested in the answer of http://stackoverflow.com/questions/4852702/do-html-websockets-maintain-an-open-connection-for-each-client-does-this-scale?

Warmest Regards,
Joel

**Comment by garyburd** [comment]
The Gorilla WebSocket package adds a small amount of memory and CPU overhead over an underlying network connection.  If it's possible to open 600,000 network connections on that configuration, then it should be possible to open that number of websocket connections.

The SO questions are about different topics. The first question asks about communication between a frontend server and backend server.  The second question asks about communication between a client and a frontend server.

**Comment by glerchundi** [comment]
Just in case someone is interested, I easily achieved 50k (concretely 51010) with a n1-standard-1 in GCE (1 vCPU, 3.75 GB) spending 2085MB for them which means:
* 3 goroutines per connection (the main one, the reader and the writer)
* 2085 * 1024 / 51010 = aprox 41kb per connection

This means that aprox. 41kb is the memory footprint for this library. CPU is neglilible, around 1% for all of them!. Using golang 1.7. Ping interval 90% of 5m. Doing nothing more than pinging.

Obviously I followed the best practices in order to get reliable results: https://www.mnot.net/blog/2011/05/18/http_benchmark_rules.

**Server:**

```
fs.file-max=1048576
fs.nr-open=1048576
net.core.somaxconn=10240
net.ipv4.tcp_mem=1048576 1048576 1048576
net.ipv4.tcp_max_syn_backlog=1024
```

**Client:**

```
fs.file-max=1048576
fs.nr-open=1048576
net.ipv4.ip_local_port_range=1024 65534
net.ipv4.tcp_mem%=1048576 1048576 1048576
```
