### ISSUE TITLE
[bug] example server fails with error when you create websocket with a protocol

### ISSUE THREAD

**Issue by kcomer** [gorilla/websocket#735]
**Describe the bug**
When I pass any value aside from `[]` as the second arg to `new Websocket(...)` I get an error.

I took a quick look at what the code was doing and it seems like the call to `read` here is returning before it should: https://github.com/gorilla/websocket/blob/c3dd95aea9779669bb3daafbd84ee0530c8ce1c1/conn.go#L798.  When no protocol is passed, the code blocks at that point.  I think it's waiting for the next frame of data and this is the point where the go code sits and waits.

When I pass the protocol, the code does not block there but instead sees 0 bytes on the call to read.  It must be getting an EOF.

A further point that may be useful for debugging is that I'm proxying these requests through Envoy and I've used Envoy to strip the `sec-websocket-protocol` protocol header before the request hits the Gorilla server.  Even when this header is stripped, I'm still seeing the same error.  This suggests that opening the websocket with the protocol changes the server request in some other way aside from adding the `sec-websocket-protocol`.

**Versions**
go version go1.17.2 darwin/amd64

**Steps to Reproduce**
```
$ git diff
diff --git a/examples/echo/server.go b/examples/echo/server.go
index 61f3dd9..51f371b 100644
--- a/examples/echo/server.go
+++ b/examples/echo/server.go
@@ -76,7 +76,7 @@ window.addEventListener("load", function(evt) {
         if (ws) {
             return false;
         }
-        ws = new WebSocket("{{.}}");
+        ws = new WebSocket("{{.}}", ["abc"]);
         ws.onopen = function(evt) {
             print("OPEN");
         }
```
Then run the example server, load the example page, and click open.

Or open devtools on the example page and create a websocket with a protocol.  Both of these fail
```
ws = new WebSocket("ws:\/\/0.0.0.0:5959\/echo", ["abc"])
ws = new WebSocket("ws:\/\/0.0.0.0:5959\/echo", "abc")
```

**Expected behavior**
Requests with any protocol should succeed.

**Comment by mamjsn** [comment]
The browser rejects the connection because the server did not select one of the client's requested protocols. 

Edit the server code to select the protocol by changing [this line](https://github.com/gorilla/websocket/blob/e8629af678b7fe13f35dff5e197de93b4148a909/examples/echo/server.go#L20):
   
    var upgrader = websocket.Upgrader{} // use default options

to 

    var upgrader = websocket.Upgrader{Subprotocols: []string{"abc"}}

The call to `p, err := c.read(2)` returns with io.EOF because the client closed the connection.  The connection translates io.EOF to close error with code 1006 per the Websocket RFC. 

When you strip the header with the Envoy server, there's no possibility of the server  responding to the client's protocol request.

**Comment by kcomer** [comment]
I see, thank you for the detailed response and sorry for my confusion!
