### ISSUE TITLE
[bug] why so many panic? Is error not working well  ?

### ISSUE THREAD

**Issue by xbyl1234** [gorilla/websocket#771]
**Describe the bug**
> A clear and concise description of what the bug is.

…

**Versions**
> Go version: `go version`
> package version: run `git rev-parse HEAD` inside the repo

…

**Steps to Reproduce**
> How can the bug be triggered?

…

**Expected behavior**
> What output or behaviour were you expecting instead?

…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Comment by garyburd** [comment]
Give examples of  panics that you think should be handled as an error.   Explain why an error is better than a panic.

**Comment by bjornnsvendsen** [comment]
@garyburd, In my opinion, shouldn't a package make decisions on how to handle errors; that is behavior that should be implemented at the application level. When you panic, to some extent you make it harder to implement alternative behavior. At least, that is how I personally like to do things.

**Comment by garyburd** [comment]
@bjornnsvendsen That’s fine as a general rule, but let’s talk about the two specific scenarios where panics are used in the package.  Which of the scenarios is better handled by an error?

**Comment by molixiaoge** [comment]
I think you only need to print the string, in this case I have to add recover to read and write functions.

**Comment by GreenMarmot** [comment]
@molixiaoge The panics indicate a logic error in your application.  Fix your application instead of adding recover.

Avoid the panic in the read function by updating your application to handle read errors. The read panic triggers after the application executes read on failed connection 1000 times.

Avoid the panic in the write function by updating your application honor the package's [concurrency constraints](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Concurrency).

**Comment by molixiaoge** [comment]
@GreenMarmot  So if my program is fine, it won't print panic?I thought it would print when I'm not sure.
