### ISSUE TITLE
[QUESTION] Regarding pongWait Time in the Examples

### ISSUE THREAD

**Issue by eltfshr** [gorilla/websocket#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the examples, it seems like new read deadline is set after receiving pong:
>ws.SetPongHandler(func(string) error { ws.SetReadDeadline(time.Now().Add(pongWait)); return nil })

My question is why is it not set right after ping is sent. This might be a misconception on my part, but shouldn't time-out be set after sending ping so that it waits for the responding pong? If it is set after receiving pong, then most of the time-out is wasted in between the interval of pings, and the real time left for new pong to respond is pongWait - pingPeriod.
CC: @riflowth, @XiaoXuxxxx, @Porping

### Expected Behavior

I expected the time-out to be set when sending ping instead of receiving pong.

**Comment by GreenMarmot** [comment]
If the application sets the deadline based on when the PONG is expected, then the application must also set the deadline in the PONG handler based on when the application expects to send the next PING.  If the deadline is not modified in the PONG handler, then read operations can timeout.  If the deadline is cleared in the PONG handler, then application can block forever on read.

The examples advance the read deadline in the PONG handler because the PONG is an indication that the peer is still live. The examples periodically send PINGs to ensure that a message is received before the deadline expires.

**Comment by riflowth** [comment]
@GreenMarmot 
I am just wondering about something and I will illustrate my confusion in the diagram below:

<img width="500" alt="image" src="https://github.com/gorilla/websocket/assets/17198802/06cfa20b-45a8-4e1c-ae8e-ab597e2680cd">

Is the `Pong Wait` not the specific time to wait after the server sends a ping to the client???
According to the implementation below, we don't start the timer to count the timeout between ping periods.

https://github.com/gorilla/websocket/blob/main/examples/chat/client.go#L114-L119

**Comment by GreenMarmot** [comment]
`pongWait` is the time to wait for the next PONG message.  The initial wait starts from the moment the connection is opened.  Thereafter, the wait starts from the moment a PONG message is received.   The wait time does not start from the moment a PING is sent.

Assuming a constant time for the PING/PONG roundtrip, PONGs are received with a deadline cushion of `(pongWait - pingInterval)` (6 seconds in the chat example).

**Comment by jaitaiwan** [comment]
I think this question has been sufficiently answered. Closing out
