### ISSUE TITLE
[FEATURE] Support Unix Domain Sockets

### ISSUE THREAD

**Issue by F1bonacc1** [gorilla/websocket#909]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe.

Using UNIX Domain Sockets (UDS) allows more flexibility in avoiding multiple projects (on the same host) collisions.
See here: https://github.com/F1bonacc1/process-compose/issues/172

### Describe the solution that you would like.

I am planning to implement both port and UDS based communication.
A user flag will select this. 
I would like to be able to do something along the following lines:
```golang
var ws *websocket.Conn
if UDS {
  ws, _, err = websocket.DefaultDialer.DialUnix("ws://unix/hello", "/tmp/path.sock", nil)
}else{
  ws, _, err = websocket.DefaultDialer.Dial("ws://localhost:8080/hello", nil)
}
ws.WriteMessage(...)
```

**Comment by GreenMarmot** [comment]
Use  [Dialer.NetDialContext](https://pkg.go.dev/github.com/gorilla/websocket#Dialer.NetDialContext) to dial a Unix domain socket. 

See [this comment](https://github.com/F1bonacc1/process-compose/issues/172#issuecomment-2036400059) for another approach to solving the underlying problem. 

The WebSocket RFC explicitly states that the protocol is layered on TCP. 

Because there are existing ways to solve OP’s problem and the feature is outside the scope of the WebSocket protocol, the proposed feature should not be added to the package.

**Comment by F1bonacc1** [comment]
Hey @GreenMarmot,
Thanks for the quick response. 
The `Dialer.NetDialContext` returns `*net.Conn` while the API works with `*wbsocket.Conn`. Is there a way to bridge or convert those?

**Comment by jaitaiwan** [comment]
wbsock.Conn contains a net.Conn

**Comment by F1bonacc1** [comment]
OK Figured it out:
```golang
d := websocket.Dialer{
	NetDialContext: func(ctx context.Context, _, _ string) (net.Conn, error) {
		return (&net.Dialer{}).DialContext(ctx, "unix", "/tmp/process-compose.sock")
	},
}
ws, _, err := d.Dial("ws://unix/hello", nil)
```
Maybe it will be useful to someone else.
